// <auto-generated />
using System;
using MatePost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatePost.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519200139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MatePost.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 50.450099999999999,
                            Longitude = 30.523399999999999,
                            Name = "Київ",
                            Region = "Київська"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 49.993499999999997,
                            Longitude = 36.230400000000003,
                            Name = "Харків",
                            Region = "Харківська"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 46.482500000000002,
                            Longitude = 30.723299999999998,
                            Name = "Одеса",
                            Region = "Одеська"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 48.464700000000001,
                            Longitude = 35.046199999999999,
                            Name = "Дніпро",
                            Region = "Дніпропетровська"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 47.838799999999999,
                            Longitude = 35.139600000000002,
                            Name = "Запоріжжя",
                            Region = "Запорізька"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 49.839700000000001,
                            Longitude = 24.029699999999998,
                            Name = "Львів",
                            Region = "Львівська"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 47.907800000000002,
                            Longitude = 33.342799999999997,
                            Name = "Кривий Ріг",
                            Region = "Дніпропетровська"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 46.975000000000001,
                            Longitude = 31.994599999999998,
                            Name = "Миколаїв",
                            Region = "Миколаївська"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 47.095599999999997,
                            Longitude = 37.549399999999999,
                            Name = "Маріуполь",
                            Region = "Донецька"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 48.573999999999998,
                            Longitude = 39.3078,
                            Name = "Луганськ",
                            Region = "Луганська"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 49.232799999999997,
                            Longitude = 28.4682,
                            Name = "Вінниця",
                            Region = "Вінницька"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 46.635399999999997,
                            Longitude = 32.616900000000001,
                            Name = "Херсон",
                            Region = "Херсонська"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 49.588299999999997,
                            Longitude = 34.551400000000001,
                            Name = "Полтава",
                            Region = "Полтавська"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 51.498199999999997,
                            Longitude = 31.289300000000001,
                            Name = "Чернігів",
                            Region = "Чернігівська"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 49.444400000000002,
                            Longitude = 32.059800000000003,
                            Name = "Черкаси",
                            Region = "Черкаська"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 50.907699999999998,
                            Longitude = 34.798099999999998,
                            Name = "Суми",
                            Region = "Сумська"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 50.2547,
                            Longitude = 28.6587,
                            Name = "Житомир",
                            Region = "Житомирська"
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 50.619900000000001,
                            Longitude = 26.2516,
                            Name = "Рівне",
                            Region = "Рівненська"
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 48.922600000000003,
                            Longitude = 24.711099999999998,
                            Name = "Івано-Франківськ",
                            Region = "Івано-Франківська"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 49.5535,
                            Longitude = 25.594799999999999,
                            Name = "Тернопіль",
                            Region = "Тернопільська"
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 50.747199999999999,
                            Longitude = 25.325399999999998,
                            Name = "Луцьк",
                            Region = "Волинська"
                        },
                        new
                        {
                            Id = 22,
                            Latitude = 48.620800000000003,
                            Longitude = 22.2879,
                            Name = "Ужгород",
                            Region = "Закарпатська"
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 49.422899999999998,
                            Longitude = 26.996400000000001,
                            Name = "Хмельницький",
                            Region = "Хмельницька"
                        },
                        new
                        {
                            Id = 24,
                            Latitude = 48.679200000000002,
                            Longitude = 26.583300000000001,
                            Name = "Кам'янець-Подільський",
                            Region = "Хмельницька"
                        },
                        new
                        {
                            Id = 25,
                            Latitude = 48.513199999999998,
                            Longitude = 32.259700000000002,
                            Name = "Кропивницький",
                            Region = "Кіровоградська"
                        });
                });

            modelBuilder.Entity("MatePost.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentCityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverCityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderCityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCityId");

                    b.HasIndex("ReceiverCityId");

                    b.HasIndex("SenderCityId");

                    b.HasIndex("SenderId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("MatePost.Models.TrackingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ParcelId");

                    b.ToTable("TrackingEvents");
                });

            modelBuilder.Entity("MatePost.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MatePost.Models.Parcel", b =>
                {
                    b.HasOne("MatePost.Models.City", "CurrentCity")
                        .WithMany()
                        .HasForeignKey("CurrentCityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MatePost.Models.City", "ReceiverCity")
                        .WithMany()
                        .HasForeignKey("ReceiverCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatePost.Models.City", "SenderCity")
                        .WithMany()
                        .HasForeignKey("SenderCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatePost.Models.User", "Sender")
                        .WithMany("SentParcels")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentCity");

                    b.Navigation("ReceiverCity");

                    b.Navigation("Sender");

                    b.Navigation("SenderCity");
                });

            modelBuilder.Entity("MatePost.Models.TrackingEvent", b =>
                {
                    b.HasOne("MatePost.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MatePost.Models.Parcel", "Parcel")
                        .WithMany("Events")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("MatePost.Models.Parcel", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MatePost.Models.User", b =>
                {
                    b.Navigation("SentParcels");
                });
#pragma warning restore 612, 618
        }
    }
}
